repository: Steeff0/Steeff0.github.io
title: Steven Gerritsen
email: steven.gerritsen@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My playgound and notes repository
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  steeff0
timezone: Europe/Amsterdam
google_analytics: "UA-10205619-2"
kofi_page: "U7U647LPC"

show_excerpts: true

# Conversion
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown Processors
kramdown:
  footnote_backlink     : ""

# Exclude from processing.
exclude:
  - node_modules
  - Docker-compose.yml
  - .gitignore
  - .dockerignore
  - update_npm.sh
  - package.json
  - package-lock.json

# collections are declared here. this renders the content in _notes and processes it
collections:
  notes:
    output: true

# My custom variables
author: Steven Gerritsen
date_format: "%d/%m/%Y"

defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
      permalink: /pages/:basename/
  -
    scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
      permalink: /notes/:slug/
      promoted: false
      discription: ""
      image: "/assets/images/notes.jpg"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /articles/:year/:slug/
      promoted: false
      discription: ""
      image: ""
  - scope:
      path:            "assets/**/*"
    values:
      sitemap:         false
