repository: Steeff0/Steeff0.github.io
title: Steven Gerritsen
email: steven.gerritsen@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My playgound and notes repository
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  steeff0
timezone: Europe/Amsterdam

show_excerpts: true

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-sitemap

social:
  linkedin: "https://www.linkedin.com/in/stevengerritsen/"
  youtube: "https://www.youtube.com/channel/UCuZHZ6ED5aWDLYFui2TVEew"
  reddit: "https://www.reddit.com/user/Steeff0/"
  steam: "https://steamcommunity.com/id/steeff0/"

# Exclude from processing.
exclude:
  - node_modules
  - Docker-compose.yml
  - .gitignore
  - .dockerignore
  - update_npm.sh
  - package.json
  - package-lock.json

# collections are declared here. this renders the content in _notes and processes it
collections:
  notes:
    output: true

# My custom variables
author: Steven Gerritsen
date_format: "%d/%m/%Y"

defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page-old"
      permalink: /pages/:basename/
  -
    scope:
      path: ""
      type: "notes"
    values:
      layout: "post-old"
      permalink: /notes/:slug/
      promoted: false
      discription: ""
      image: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-old"
      permalink: /articles/:year/:slug/
      promoted: false
      discription: ""
      image: ""
  - scope:
      path:            "assets/**/*"
    values:
      sitemap:         false
